name: DASHABI_MAIN

on:
  schedule:
    - cron: '5 22,23,0-15/1 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Car/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./Dashabi/dsb_main.py
        env:
            dashabi_main_url: ${{ secrets.dashabi_main_url }}
            dashabi_hd: ${{ secrets.dashabi_hd }}
            dashabi_bd: ${{ secrets.dashabi_bd }}
