name: DASHABI_666

on:
  schedule:
    - cron: '20 0-16 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Car/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./Dashabi/dsb_666.py
        env:
            dashabi_666_url: ${{ secrets.dashabi_666_url }}
            dashabi_hd: ${{ secrets.dashabi_hd }}
            dashabi_666_bd: ${{ secrets.dashabi_666_bd }}
