name: NewsQB

on:
  schedule:
    - cron: '20 22,5 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./NewsQB/公众号iosrule.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./NewsQB/newsqb.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            news_url: ${{ secrets.news_url }}
            news_hd: ${{ secrets.news_hd }}
            news_bt: ${{ secrets.news_bt }}
 
