name: Q_Qsub

on:
  schedule:
    - cron: '30 16,17,4 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Q_Qmain/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./Q_Qmain/Q_Qsub.py
        env:
            ios_newurl: ${{ secrets.ios_newurl }}
            ios_newhd: ${{ secrets.ios_newhd }}
            ios_newbd: ${{ secrets.ios_newbd }}
            ios_newbt: ${{ secrets.ios_newbt }}
