name: Sub_Q

on:
  schedule:
    - cron: '*/10 * * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./qqread/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./qqread/SubQ.py
        env:
            ios_newurl: ${{ secrets.ios_newurl }}
            ios_newhd: ${{ secrets.ios_newhd }}
            ios_newbd: ${{ secrets.ios_newbd }}
            ios_newbt: ${{ secrets.ios_newbt }}
