name: TG_CS

on:
  schedule:
    - cron: '*45 3-8* * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Car/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./CeShi/cs.py 
        env:
            tg_bot_id: ${{ secrets.tg_bot_id }}
            tg_member_id: ${{ secrets.tg_member_id }}
