name: xb_notice

on:
  schedule:
    - cron: '*/35 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Lucky/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./XV_APP/xb_notice.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_SEVER_JIANG: ${{ secrets.DJJ_SEVER_JIANG }}
            DJJ_TELE_COOKIE: ${{ secrets.DJJ_TELE_COOKIE }}
            xb_sub_url: ${{ secrets.xb_sub_url }}
            xb_sub_hd: ${{ secrets.xb_sub_hd }}
