name: 整点报时

on:
  schedule:
    - cron: '10 15 * * *'
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'py'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: '安装库'
        run: pip install -r ./Car/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./Dashabi/BWP.py
        env:
            dashabi_main_url: ${{ secrets.dashabi_main_url }}
            dashabi_hd: ${{ secrets.dashabi_hd }}
            dashabi_bd: ${{ secrets.dashabi_bd }}
